# -*- coding: utf-8 -*-
"""netflix_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaijdTJKfGUUnuEod9vVN29F17IBbBir
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/netflix_titles.csv')
df.head()

df.tail()

df.shape

df.info()

df.describe()

df.describe(include="O")

df.isnull().sum()
df
df.head()

df.iloc[10]

df.reset_index(inplace=True)
df

df.set_index("show_id", inplace=True)
df

df[["type"]]

df[["type", "title"]]

df[df["type"] == "Movie"]

df[(df["type"]== "Movie") & (df["release_year"] > 2016)]

df.fillna('unknown',inplace=True)
df

df.rename(columns={"release_year" : "Year"}, inplace=True)
df

df[(df["type"] == "Movie") & (df["country"] == "United States") & (df["Year"] > 2010)]

df["Year"].max()

df["Year"].min()

df["country"].mode()[0]

df["type"].mode()[0]

df.to_csv("updated_cleaned.csv", index=False)